tokens=(
    "int",
    "float",
    "string",
    "bool",
    "output",
    "input",
    "get",
    "post",
    "g_p",
    "#include",
    "for",
    "while",
    "until",
    "function",
    "class",
    "++",
    "--",
    "**",
    "+=",
    "-=",
    "*=",
    "/="
    "+",
    "-",
    "*",
    "/",
    "//",
    "<",
    ">",
    ":",
    "::",
    "{",
    "(",
    ")",
    "}",
    "return",
    "break",
    "randint",
    "randfloat",
    "root",
    "button",
    "img",
    "pack",
    "place",
    "MenuBar",
    "menu",
    "mainloop",
    "kbhit",
    "getch"
)
def complier(code:str):
    tokens=[]
    code=code.splitlines()
    i=0
    while i<len(code):
        j=0
        while j<len(code[i]):
            for k in tokens:
                if code[i][j]==k:
                    tokens.append(k)
